-- Esquema inicial de Alex-Rifas.
-- SQL portable: se ejecuta igual en PostgreSQL (producción) y en H2 modo PostgreSQL (dev y tests).
-- Regla de oro: nunca se edita una migración ya aplicada; los cambios van en V2, V3, ...

CREATE TABLE usuarios (
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre             VARCHAR(80)  NOT NULL,
    apellido           VARCHAR(80)  NOT NULL,
    telefono           VARCHAR(20)  NOT NULL,
    correo             VARCHAR(160) NOT NULL,
    contrasena_hash    VARCHAR(100) NOT NULL,
    rol                VARCHAR(20)  NOT NULL,
    activo             BOOLEAN      NOT NULL,
    fecha_nacimiento   DATE,
    acepto_terminos_en TIMESTAMP WITH TIME ZONE,
    creado_en          TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT uk_usuarios_correo UNIQUE (correo)
);

-- El token en claro NUNCA se guarda: solo su hash SHA-256.
CREATE TABLE refresh_tokens (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    token_hash  VARCHAR(64) NOT NULL,
    usuario_id  BIGINT      NOT NULL,
    expira_en   TIMESTAMP WITH TIME ZONE NOT NULL,
    revocado    BOOLEAN     NOT NULL,
    creado_en   TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT uk_refresh_tokens_hash UNIQUE (token_hash),
    CONSTRAINT fk_refresh_tokens_usuario FOREIGN KEY (usuario_id) REFERENCES usuarios (id)
);
CREATE INDEX ix_refresh_tokens_usuario ON refresh_tokens (usuario_id);

CREATE TABLE rifas (
    id                        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    codigo_publico            VARCHAR(16)   NOT NULL,
    organizador_id            BIGINT        NOT NULL,
    titulo                    VARCHAR(120)  NOT NULL,
    descripcion               VARCHAR(4000),
    imagen_url                VARCHAR(500),
    precio_boleto             NUMERIC(12,2) NOT NULL,
    moneda                    VARCHAR(3)    NOT NULL,
    cantidad_boletos          INTEGER       NOT NULL,
    estado                    VARCHAR(20)   NOT NULL,
    fecha_sorteo              TIMESTAMP WITH TIME ZONE NOT NULL,
    cierre_ventas_en          TIMESTAMP WITH TIME ZONE NOT NULL,
    maximo_boletos_por_compra INTEGER       NOT NULL,
    metodo_sorteo             VARCHAR(20)   NOT NULL,
    loteria_nombre            VARCHAR(80),
    numero_autorizacion       VARCHAR(60),
    entidad_autorizadora      VARCHAR(120),
    creada_en                 TIMESTAMP WITH TIME ZONE NOT NULL,
    actualizada_en            TIMESTAMP WITH TIME ZONE NOT NULL,
    publicada_en              TIMESTAMP WITH TIME ZONE,
    version                   BIGINT        NOT NULL,
    CONSTRAINT uk_rifas_codigo UNIQUE (codigo_publico),
    CONSTRAINT fk_rifas_organizador FOREIGN KEY (organizador_id) REFERENCES usuarios (id),
    CONSTRAINT ck_rifas_precio CHECK (precio_boleto > 0),
    CONSTRAINT ck_rifas_cantidad CHECK (cantidad_boletos >= 10)
);
CREATE INDEX ix_rifas_estado_sorteo ON rifas (estado, fecha_sorteo);
CREATE INDEX ix_rifas_organizador ON rifas (organizador_id);

CREATE TABLE premios (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    rifa_id         BIGINT       NOT NULL,
    posicion        INTEGER      NOT NULL,
    nombre          VARCHAR(120) NOT NULL,
    descripcion     VARCHAR(1000),
    valor_estimado  NUMERIC(14,2),
    imagen_url      VARCHAR(500),
    CONSTRAINT uk_premios_rifa_posicion UNIQUE (rifa_id, posicion),
    CONSTRAINT fk_premios_rifa FOREIGN KEY (rifa_id) REFERENCES rifas (id)
);

CREATE TABLE compras (
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    codigo_publico     VARCHAR(16)   NOT NULL,
    rifa_id            BIGINT        NOT NULL,
    usuario_id         BIGINT,
    comprador_nombre   VARCHAR(120)  NOT NULL,
    comprador_telefono VARCHAR(20)   NOT NULL,
    comprador_correo   VARCHAR(160),
    estado             VARCHAR(25)   NOT NULL,
    metodo_pago        VARCHAR(20),
    cantidad           INTEGER       NOT NULL,
    total              NUMERIC(14,2) NOT NULL,
    numeros            VARCHAR(1000) NOT NULL,
    reservado_hasta    TIMESTAMP WITH TIME ZONE NOT NULL,
    creada_en          TIMESTAMP WITH TIME ZONE NOT NULL,
    pagada_en          TIMESTAMP WITH TIME ZONE,
    confirmada_por_id  BIGINT,
    referencia_pago    VARCHAR(120),
    nota               VARCHAR(500),
    version            BIGINT        NOT NULL,
    CONSTRAINT uk_compras_codigo UNIQUE (codigo_publico),
    CONSTRAINT fk_compras_rifa FOREIGN KEY (rifa_id) REFERENCES rifas (id),
    CONSTRAINT fk_compras_usuario FOREIGN KEY (usuario_id) REFERENCES usuarios (id)
);
CREATE INDEX ix_compras_rifa_estado ON compras (rifa_id, estado);
CREATE INDEX ix_compras_telefono_estado ON compras (comprador_telefono, estado);
CREATE INDEX ix_compras_usuario ON compras (usuario_id);
CREATE INDEX ix_compras_vencimiento ON compras (estado, reservado_hasta);

-- Una fila por número de cada rifa. La restricción UNIQUE (rifa_id, numero) más el bloqueo
-- de fila (SELECT ... FOR UPDATE) al reservar es lo que garantiza que un número jamás se
-- venda dos veces, incluso con miles de compradores a la vez.
CREATE TABLE boletos (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    rifa_id          BIGINT      NOT NULL,
    numero           INTEGER     NOT NULL,
    estado           VARCHAR(15) NOT NULL,
    compra_id        BIGINT,
    reservado_hasta  TIMESTAMP WITH TIME ZONE,
    CONSTRAINT uk_boletos_rifa_numero UNIQUE (rifa_id, numero),
    CONSTRAINT fk_boletos_rifa FOREIGN KEY (rifa_id) REFERENCES rifas (id),
    CONSTRAINT fk_boletos_compra FOREIGN KEY (compra_id) REFERENCES compras (id)
);
CREATE INDEX ix_boletos_compra ON boletos (compra_id);
CREATE INDEX ix_boletos_rifa_estado ON boletos (rifa_id, estado);

CREATE TABLE pagos_wompi (
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    compra_id          BIGINT      NOT NULL,
    referencia         VARCHAR(80) NOT NULL,
    monto_en_centavos  BIGINT      NOT NULL,
    moneda             VARCHAR(3)  NOT NULL,
    id_transaccion     VARCHAR(80),
    estado             VARCHAR(15) NOT NULL,
    creado_en          TIMESTAMP WITH TIME ZONE NOT NULL,
    actualizado_en     TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT uk_pagos_wompi_referencia UNIQUE (referencia),
    CONSTRAINT fk_pagos_wompi_compra FOREIGN KEY (compra_id) REFERENCES compras (id)
);
CREATE INDEX ix_pagos_wompi_compra ON pagos_wompi (compra_id);

-- Un premio solo tiene un ganador y un boleto solo puede ganar un premio.
CREATE TABLE ganadores (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    rifa_id             BIGINT      NOT NULL,
    premio_id           BIGINT      NOT NULL,
    boleto_id           BIGINT      NOT NULL,
    numero              INTEGER     NOT NULL,
    compra_id           BIGINT      NOT NULL,
    metodo              VARCHAR(20) NOT NULL,
    evidencia           VARCHAR(500),
    registrado_por_id   BIGINT,
    registrado_en       TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT uk_ganadores_premio UNIQUE (premio_id),
    CONSTRAINT uk_ganadores_boleto UNIQUE (boleto_id),
    CONSTRAINT fk_ganadores_rifa FOREIGN KEY (rifa_id) REFERENCES rifas (id),
    CONSTRAINT fk_ganadores_premio FOREIGN KEY (premio_id) REFERENCES premios (id),
    CONSTRAINT fk_ganadores_boleto FOREIGN KEY (boleto_id) REFERENCES boletos (id),
    CONSTRAINT fk_ganadores_compra FOREIGN KEY (compra_id) REFERENCES compras (id)
);
CREATE INDEX ix_ganadores_rifa ON ganadores (rifa_id);

-- Bitácora de solo-inserción de las acciones sensibles.
CREATE TABLE auditoria (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fecha       TIMESTAMP WITH TIME ZONE NOT NULL,
    actor_id    BIGINT,
    actor_rol   VARCHAR(20),
    accion      VARCHAR(60) NOT NULL,
    entidad     VARCHAR(40),
    entidad_id  BIGINT,
    detalle     VARCHAR(1000)
);
CREATE INDEX ix_auditoria_fecha ON auditoria (fecha);
CREATE INDEX ix_auditoria_entidad ON auditoria (entidad, entidad_id);
